Side:               # LVL1 - Though in practice, often uses lvl3 formations
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Army:               # LVL2 - Though in practice, often uses lvl3 formations
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Corps:              # LVL3
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Infantry Division:  # LVL4
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Cavalry Division:   # LVL4
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Artillery Division: # LVL4
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Infantry Brigade:   # LVL5
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Cavalry Brigade:    # LVL5
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Artillery Brigade:  # LVL5
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Infantry Regiment:  # LVL6
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Cavalry Squadron:   # LVL6
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
Artillery Battery:  # LVL6
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
  - "DRIL_Lvl6_Inf_Column"
